# Generated by Django 4.1.5 on 2023-01-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('english', '0001_initial'),
        ('hanja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanjaKorean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanja.hanja')),
                ('korean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.english')),
            ],
        ),
    ]
