# Generated by Django 4.1.5 on 2023-01-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hanja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanjaAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_hanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated', to='hanja.hanja')),
                ('initial_hanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='hanja.hanja')),
            ],
        ),
    ]
