# Generated by Django 4.1.5 on 2023-01-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('korean_translation', models.CharField(max_length=255)),
                ('korean_pronunciation', models.CharField(max_length=255)),
                ('strokes', models.IntegerField()),
                ('korean_etymology', models.TextField()),
                ('english_etymology', models.TextField()),
                ('french_etymology', models.TextField()),
                ('radical', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hanja.hanja')),
            ],
        ),
    ]
